// File: lib/types/database.ts
// Auto-generated by `npm run db:types`. Hand-maintained here for first run.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: { id: string; display_name: string | null; created_at: string };
        Insert: { id: string; display_name?: string | null };
        Update: { display_name?: string | null };
      };
      products: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          last_used_at: string;
          created_at: string;
        };
        Insert: { user_id: string; name: string; last_used_at?: string };
        Update: { name?: string; last_used_at?: string };
      };
      daily_entries: {
        Row: {
          id: string;
          user_id: string;
          entry_date: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: { user_id: string; entry_date: string };
        Update: { entry_date?: string; deleted_at?: string | null };
      };
      sale_items: {
        Row: {
          id: string;
          entry_id: string;
          product_name: string;
          quantity_kg: number;
          price_per_kg: number;
          total: number;
          sort_order: number;
        };
        Insert: {
          entry_id: string;
          product_name: string;
          quantity_kg: number;
          price_per_kg: number;
          sort_order?: number;
        };
        Update: Partial<Database['public']['Tables']['sale_items']['Insert']>;
      };
      extra_incomes: {
        Row: {
          id: string;
          entry_id: string;
          description: string;
          amount: number;
          sort_order: number;
        };
        Insert: {
          entry_id: string;
          description: string;
          amount: number;
          sort_order?: number;
        };
        Update: Partial<
          Database['public']['Tables']['extra_incomes']['Insert']
        >;
      };
      purchase_items: {
        Row: {
          id: string;
          entry_id: string;
          product_name: string;
          quantity_kg: number;
          price_per_kg: number;
          total: number;
          sort_order: number;
        };
        Insert: {
          entry_id: string;
          product_name: string;
          quantity_kg: number;
          price_per_kg: number;
          sort_order?: number;
        };
        Update: Partial<
          Database['public']['Tables']['purchase_items']['Insert']
        >;
      };
      extra_expenses: {
        Row: {
          id: string;
          entry_id: string;
          description: string;
          amount: number;
          sort_order: number;
        };
        Insert: {
          entry_id: string;
          description: string;
          amount: number;
          sort_order?: number;
        };
        Update: Partial<
          Database['public']['Tables']['extra_expenses']['Insert']
        >;
      };
    };
    Views: {
      daily_summary: {
        Row: {
          entry_id: string;
          user_id: string;
          entry_date: string;
          total_income: number;
          total_expense: number;
          total_kg_sold: number;
        };
      };
    };
    Functions: {
      upsert_daily_entry: {
        Args: {
          p_entry_date: string;
          p_sales: Json;
          p_incomes: Json;
          p_purchases: Json;
          p_expenses: Json;
        };
        Returns: string;
      };
      top_products: {
        Args: { p_from: string; p_to: string; p_limit?: number };
        Returns: {
          product_name: string;
          total_amount: number;
          total_kg: number;
        }[];
      };
      expense_breakdown: {
        Args: { p_from: string; p_to: string };
        Returns: { purchase_total: number; other_total: number }[];
      };
    };
  };
}
